title: Naming the Code
markdown: kramdown

# for atom feed
author:
  name: Aldayr Ruiz
  email: aldayrruiz@proton.me

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:categories/:title

exclude: ["*.py", "sitemap.xml", "feed.xml", "LICENSE", "README.md"]
